/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BridgeManagementContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getValidators"
      | "governor"
      | "owner"
      | "relayer"
      | "securityGuard"
      | "setGovernor"
      | "setOwner"
      | "setRelayer"
      | "setSecurityGuard"
      | "setValidators"
      | "validatorThreshold"
      | "validators"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "SetGovernor"
      | "SetOwner"
      | "SetRelayer"
      | "SetSecurityGuard"
      | "SetValidators"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getValidators",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "securityGuard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecurityGuard",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidators",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "securityGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSecurityGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
}

export namespace SetGovernorEvent {
  export type InputTuple = [governor: AddressLike];
  export type OutputTuple = [governor: string];
  export interface OutputObject {
    governor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetOwnerEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetRelayerEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetSecurityGuardEvent {
  export type InputTuple = [securityGuard: AddressLike];
  export type OutputTuple = [securityGuard: string];
  export interface OutputObject {
    securityGuard: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetValidatorsEvent {
  export type InputTuple = [validators: AddressLike[], threshold: BigNumberish];
  export type OutputTuple = [validators: string[], threshold: bigint];
  export interface OutputObject {
    validators: string[];
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeManagementContract extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeManagementContract;
  waitForDeployment(): Promise<this>;

  interface: BridgeManagementContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getValidators: TypedContractMethod<[], [string[]], "view">;

  governor: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  relayer: TypedContractMethod<[], [string], "view">;

  securityGuard: TypedContractMethod<[], [string], "view">;

  setGovernor: TypedContractMethod<
    [_governor: AddressLike],
    [void],
    "nonpayable"
  >;

  setOwner: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  setRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  setSecurityGuard: TypedContractMethod<
    [_securityGuard: AddressLike],
    [void],
    "nonpayable"
  >;

  setValidators: TypedContractMethod<
    [_validators: AddressLike[], threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  validatorThreshold: TypedContractMethod<[], [bigint], "view">;

  validators: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getValidators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "governor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "securityGuard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGovernor"
  ): TypedContractMethod<[_governor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOwner"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSecurityGuard"
  ): TypedContractMethod<[_securityGuard: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValidators"
  ): TypedContractMethod<
    [_validators: AddressLike[], threshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validatorThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "SetGovernor"
  ): TypedContractEvent<
    SetGovernorEvent.InputTuple,
    SetGovernorEvent.OutputTuple,
    SetGovernorEvent.OutputObject
  >;
  getEvent(
    key: "SetOwner"
  ): TypedContractEvent<
    SetOwnerEvent.InputTuple,
    SetOwnerEvent.OutputTuple,
    SetOwnerEvent.OutputObject
  >;
  getEvent(
    key: "SetRelayer"
  ): TypedContractEvent<
    SetRelayerEvent.InputTuple,
    SetRelayerEvent.OutputTuple,
    SetRelayerEvent.OutputObject
  >;
  getEvent(
    key: "SetSecurityGuard"
  ): TypedContractEvent<
    SetSecurityGuardEvent.InputTuple,
    SetSecurityGuardEvent.OutputTuple,
    SetSecurityGuardEvent.OutputObject
  >;
  getEvent(
    key: "SetValidators"
  ): TypedContractEvent<
    SetValidatorsEvent.InputTuple,
    SetValidatorsEvent.OutputTuple,
    SetValidatorsEvent.OutputObject
  >;

  filters: {
    "SetGovernor(address)": TypedContractEvent<
      SetGovernorEvent.InputTuple,
      SetGovernorEvent.OutputTuple,
      SetGovernorEvent.OutputObject
    >;
    SetGovernor: TypedContractEvent<
      SetGovernorEvent.InputTuple,
      SetGovernorEvent.OutputTuple,
      SetGovernorEvent.OutputObject
    >;

    "SetOwner(address)": TypedContractEvent<
      SetOwnerEvent.InputTuple,
      SetOwnerEvent.OutputTuple,
      SetOwnerEvent.OutputObject
    >;
    SetOwner: TypedContractEvent<
      SetOwnerEvent.InputTuple,
      SetOwnerEvent.OutputTuple,
      SetOwnerEvent.OutputObject
    >;

    "SetRelayer(address)": TypedContractEvent<
      SetRelayerEvent.InputTuple,
      SetRelayerEvent.OutputTuple,
      SetRelayerEvent.OutputObject
    >;
    SetRelayer: TypedContractEvent<
      SetRelayerEvent.InputTuple,
      SetRelayerEvent.OutputTuple,
      SetRelayerEvent.OutputObject
    >;

    "SetSecurityGuard(address)": TypedContractEvent<
      SetSecurityGuardEvent.InputTuple,
      SetSecurityGuardEvent.OutputTuple,
      SetSecurityGuardEvent.OutputObject
    >;
    SetSecurityGuard: TypedContractEvent<
      SetSecurityGuardEvent.InputTuple,
      SetSecurityGuardEvent.OutputTuple,
      SetSecurityGuardEvent.OutputObject
    >;

    "SetValidators(address[],uint256)": TypedContractEvent<
      SetValidatorsEvent.InputTuple,
      SetValidatorsEvent.OutputTuple,
      SetValidatorsEvent.OutputObject
    >;
    SetValidators: TypedContractEvent<
      SetValidatorsEvent.InputTuple,
      SetValidatorsEvent.OutputTuple,
      SetValidatorsEvent.OutputObject
    >;
  };
}
