/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tests from "./tests";
export type { tests };
export type { BridgeContract } from "./BridgeContract";
export type { BridgeManagementContract } from "./BridgeManagementContract";
export type { BridgeProxy } from "./BridgeProxy";
export type { BridgeStorage } from "./BridgeStorage";
