/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tests from "./tests";
export type { tests };
export type { BridgeImpl } from "./BridgeImpl";
export type { BridgeManagementContract } from "./BridgeManagementContract";
export type { BridgeStorage } from "./BridgeStorage";
