/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TestBridgeStorageV2,
  TestBridgeStorageV2Interface,
} from "../../../contracts/tests/TestBridgeStorageV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    name: "claimableGas",
    outputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "amount",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "gasBridge",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
        ],
        internalType: "struct TestBridgeStorageV1.State",
        name: "depositState",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
        ],
        internalType: "struct TestBridgeStorageV1.State",
        name: "withdrawalState",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxAmount",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "maxDepositsPerDistribution",
            type: "uint8",
          },
          {
            internalType: "uint256[2]",
            name: "gap",
            type: "uint256[2]",
          },
        ],
        internalType: "struct TestBridgeStorageV1.Config",
        name: "config",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "locked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "managementContract",
    outputs: [
      {
        internalType: "contract BridgeManagementContract",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "proxyGap",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506103bf806100206000396000f3fe608060405234801561001057600080fd5b506004361061007d5760003560e01c8063c3c5a5471161005b578063c3c5a5471461014a578063cabfe7c61461017d578063cf3090121461019e578063f7e3d1b4146101ab57600080fd5b80634420e4861461008257806360f72e5a146100b6578063b3e5cc4a1461011f575b600080fd5b6100b461009036600461027f565b6001600160a01b03166000908152600f60205260409020805460ff19166001179055565b005b6100f26100c43660046102af565b600d602052600090815260409020546001600160a01b03811690600160a01b900467ffffffffffffffff1682565b604080516001600160a01b03909316835267ffffffffffffffff9091166020830152015b60405180910390f35b600254610132906001600160a01b031681565b6040516001600160a01b039091168152602001610116565b61016d61015836600461027f565b600f6020526000908152604090205460ff1681565b6040519015158152602001610116565b61019061018b3660046102d9565b6101c2565b604051908152602001610116565b600e5461016d9060ff1681565b6101b36101d9565b604051610116939291906102f2565b600081600281106101d257600080fd5b0154905081565b6040805180820182526003805467ffffffffffffffff908116835260045460208085019190915284518086018652600554909216825260065482820152845160a0810186526007805482526008549282019290925260095481870152600a5460ff166060820152855180870196879052949592949092608084019190600b9060029082845b81548152602001906001019080831161025e57505050505081525050905083565b60006020828403121561029157600080fd5b81356001600160a01b03811681146102a857600080fd5b9392505050565b6000602082840312156102c157600080fd5b813567ffffffffffffffff811681146102a857600080fd5b6000602082840312156102eb57600080fd5b5035919050565b835167ffffffffffffffff168152602080850151908201526101408101835167ffffffffffffffff166040830152602084015160608301528251608083015260208084015160a0840152604084015160c084015260ff60608501511660e08401526080840151610100840160005b600281101561037d57825182529183019190830190600101610360565b5050505094935050505056fea2646970667358221220a28710e14140318b9e6ab751e2e9846e2d8eaa3add709b5bfa243b33a22783a664736f6c63430008140033";

type TestBridgeStorageV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestBridgeStorageV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestBridgeStorageV2__factory extends ContractFactory {
  constructor(...args: TestBridgeStorageV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestBridgeStorageV2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TestBridgeStorageV2__factory {
    return super.connect(runner) as TestBridgeStorageV2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestBridgeStorageV2Interface {
    return new Interface(_abi) as TestBridgeStorageV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestBridgeStorageV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TestBridgeStorageV2;
  }
}
