/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../common";
import type { BridgeProxy, BridgeProxyInterface } from "../BridgeProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_implementation",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newImplementation",
        type: "address",
      },
    ],
    name: "upgrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161029c38038061029c83398101604081905261002f9161005d565b600080546001600160a01b039092166001600160a01b0319928316179055600180549091163317905561008d565b60006020828403121561006f57600080fd5b81516001600160a01b038116811461008657600080fd5b9392505050565b6102008061009c6000396000f3fe6080604052600436106100385760003560e01c80630900f010146100b65780635c60da1b146100d65780638da5cb5b146101125761003f565b3661003f57005b6000546001600160a01b03168061008f5760405162461bcd60e51b815260206004820152600f60248201526e139bdd081a5b5c1b195b595b9d1959608a1b60448201526064015b60405180910390fd5b60405136600082376000803683855af43d806000843e8180156100b0578184f35b8184fd5b005b3480156100c257600080fd5b506100b46100d136600461019a565b610132565b3480156100e257600080fd5b506000546100f6906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b34801561011e57600080fd5b506001546100f6906001600160a01b031681565b6001546001600160a01b031633146101785760405162461bcd60e51b81526020600482015260096024820152682737ba1037bbb732b960b91b6044820152606401610086565b600080546001600160a01b0319166001600160a01b0392909216919091179055565b6000602082840312156101ac57600080fd5b81356001600160a01b03811681146101c357600080fd5b939250505056fea2646970667358221220a0f2d6ab3da1df5af60594c934a76d6226e25d04fb71724304aa26f00b893d8764736f6c63430008140033";

type BridgeProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BridgeProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BridgeProxy__factory extends ContractFactory {
  constructor(...args: BridgeProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _implementation: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_implementation, overrides || {});
  }
  override deploy(
    _implementation: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_implementation, overrides || {}) as Promise<
      BridgeProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BridgeProxy__factory {
    return super.connect(runner) as BridgeProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BridgeProxyInterface {
    return new Interface(_abi) as BridgeProxyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BridgeProxy {
    return new Contract(address, _abi, runner) as unknown as BridgeProxy;
  }
}
