/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bridgeContractSol from "./BridgeContract.sol";
export { AppLogsBridgeContract__factory } from "./AppLogsBridgeContract__factory";
