/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Test, TestInterface } from "../Test";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "_nonce",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_amount",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "test",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610328806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806360a3433014610030575b600080fd5b61004a60048036038101906100459190610132565b610060565b6040516100579190610215565b60405180910390f35b6060838383604051602001610077939291906102b5565b60405160208183030381529060405290509392505050565b600080fd5b600067ffffffffffffffff82169050919050565b6100b181610094565b81146100bc57600080fd5b50565b6000813590506100ce816100a8565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100ff826100d4565b9050919050565b61010f816100f4565b811461011a57600080fd5b50565b60008135905061012c81610106565b92915050565b60008060006060848603121561014b5761014a61008f565b5b6000610159868287016100bf565b935050602061016a868287016100bf565b925050604061017b8682870161011d565b9150509250925092565b600081519050919050565b600082825260208201905092915050565b60005b838110156101bf5780820151818401526020810190506101a4565b60008484015250505050565b6000601f19601f8301169050919050565b60006101e782610185565b6101f18185610190565b93506102018185602086016101a1565b61020a816101cb565b840191505092915050565b6000602082019050818103600083015261022f81846101dc565b905092915050565b60008160c01b9050919050565b600061024f82610237565b9050919050565b61026761026282610094565b610244565b82525050565b60008160601b9050919050565b60006102858261026d565b9050919050565b60006102978261027a565b9050919050565b6102af6102aa826100f4565b61028c565b82525050565b60006102c18286610256565b6008820191506102d18285610256565b6008820191506102e1828461029e565b60148201915081905094935050505056fea26469706673582212201943752314f82a90b885078e9cb53cdeb31fda2b19d06f5b6a4e959c62dbf84e64736f6c63430008150033";

type TestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Test__factory extends ContractFactory {
  constructor(...args: TestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Test & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Test__factory {
    return super.connect(runner) as Test__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestInterface {
    return new Interface(_abi) as TestInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Test {
    return new Contract(address, _abi, runner) as unknown as Test;
  }
}
