/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  BridgeStorage,
  BridgeStorageInterface,
} from "../../contracts/BridgeStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    name: "claimableGas",
    outputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "amount",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "gasBridge",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
        ],
        internalType: "struct BridgeStorage.State",
        name: "depositState",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
        ],
        internalType: "struct BridgeStorage.State",
        name: "withdrawalState",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxAmount",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "maxDepositsPerDistribution",
            type: "uint8",
          },
          {
            internalType: "uint256[2]",
            name: "gap",
            type: "uint256[2]",
          },
        ],
        internalType: "struct BridgeStorage.Config",
        name: "config",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "locked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "managementContract",
    outputs: [
      {
        internalType: "contract BridgeManagementContract",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "proxyGap",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610319806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806360f72e5a1461005c578063b3e5cc4a146100c5578063cabfe7c6146100f0578063cf30901214610111578063f7e3d1b41461012e575b600080fd5b61009861006a366004610202565b600d602052600090815260409020546001600160a01b03811690600160a01b900467ffffffffffffffff1682565b604080516001600160a01b03909316835267ffffffffffffffff9091166020830152015b60405180910390f35b6002546100d8906001600160a01b031681565b6040516001600160a01b0390911681526020016100bc565b6101036100fe366004610233565b610145565b6040519081526020016100bc565b600e5461011e9060ff1681565b60405190151581526020016100bc565b61013661015c565b6040516100bc9392919061024c565b6000816002811061015557600080fd5b0154905081565b6040805180820182526003805467ffffffffffffffff908116835260045460208085019190915284518086018652600554909216825260065482820152845160a0810186526007805482526008549282019290925260095481870152600a5460ff166060820152855180870196879052949592949092608084019190600b9060029082845b8154815260200190600101908083116101e157505050505081525050905083565b60006020828403121561021457600080fd5b813567ffffffffffffffff8116811461022c57600080fd5b9392505050565b60006020828403121561024557600080fd5b5035919050565b835167ffffffffffffffff168152602080850151908201526101408101835167ffffffffffffffff166040830152602084015160608301528251608083015260208084015160a0840152604084015160c084015260ff60608501511660e08401526080840151610100840160005b60028110156102d7578251825291830191908301906001016102ba565b5050505094935050505056fea26469706673582212202f598404cbed07617e35e43481bfcabc5cd21bb11716dd4128e163e6831341b064736f6c63430008140033";

type BridgeStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BridgeStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BridgeStorage__factory extends ContractFactory {
  constructor(...args: BridgeStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BridgeStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BridgeStorage__factory {
    return super.connect(runner) as BridgeStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BridgeStorageInterface {
    return new Interface(_abi) as BridgeStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BridgeStorage {
    return new Contract(address, _abi, runner) as unknown as BridgeStorage;
  }
}
