/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tests from "./tests";
export { BridgeImpl__factory } from "./BridgeImpl__factory";
export { BridgeManagementContract__factory } from "./BridgeManagementContract__factory";
export { BridgeStorage__factory } from "./BridgeStorage__factory";
