/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestBridgeImplV2 } from "./TestBridgeImplV2";
export type { TestBridgeStorageV1 } from "./TestBridgeStorageV1";
export type { TestBridgeStorageV2 } from "./TestBridgeStorageV2";
export type { TestPayableContract } from "./TestPayableContract";
