/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TestBridgeStorageV1 {
  export type StateStruct = { nonce: BigNumberish; root: BytesLike };

  export type StateStructOutput = [nonce: bigint, root: string] & {
    nonce: bigint;
    root: string;
  };

  export type ConfigStruct = {
    fee: BigNumberish;
    minAmount: BigNumberish;
    maxAmount: BigNumberish;
    maxDepositsPerDistribution: BigNumberish;
    gap: [BigNumberish, BigNumberish];
  };

  export type ConfigStructOutput = [
    fee: bigint,
    minAmount: bigint,
    maxAmount: bigint,
    maxDepositsPerDistribution: bigint,
    gap: [bigint, bigint]
  ] & {
    fee: bigint;
    minAmount: bigint;
    maxAmount: bigint;
    maxDepositsPerDistribution: bigint;
    gap: [bigint, bigint];
  };
}

export interface TestBridgeStorageV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "claimableGas"
      | "endUpgradeability"
      | "gasBridge"
      | "initialize"
      | "isRegistered"
      | "locked"
      | "managementContract"
      | "proxiableUUID"
      | "register"
      | "upgradeToAndCall"
      | "upgradeabilityEnded"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Initialized" | "Upgraded"): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableGas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endUpgradeability",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gasBridge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, TestBridgeStorageV1.ConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "locked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "managementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeabilityEnded",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endUpgradeability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasBridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "managementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeabilityEnded",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestBridgeStorageV2 extends BaseContract {
  connect(runner?: ContractRunner | null): TestBridgeStorageV2;
  waitForDeployment(): Promise<this>;

  interface: TestBridgeStorageV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  claimableGas: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;

  endUpgradeability: TypedContractMethod<[], [void], "nonpayable">;

  gasBridge: TypedContractMethod<
    [],
    [
      [
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: TestBridgeStorageV1.StateStructOutput;
        withdrawalState: TestBridgeStorageV1.StateStructOutput;
        config: TestBridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _managementContract: AddressLike,
      config: TestBridgeStorageV1.ConfigStruct
    ],
    [void],
    "nonpayable"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  locked: TypedContractMethod<[], [boolean], "view">;

  managementContract: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  upgradeabilityEnded: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimableGas"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "endUpgradeability"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gasBridge"
  ): TypedContractMethod<
    [],
    [
      [
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: TestBridgeStorageV1.StateStructOutput;
        withdrawalState: TestBridgeStorageV1.StateStructOutput;
        config: TestBridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _managementContract: AddressLike,
      config: TestBridgeStorageV1.ConfigStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "locked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "managementContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "upgradeabilityEnded"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
