/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TestBridgeImplV2 {
  export type SignatureStruct = { v: BigNumberish; r: BytesLike; s: BytesLike };

  export type SignatureStructOutput = [v: bigint, r: string, s: string] & {
    v: bigint;
    r: string;
    s: string;
  };

  export type DepositDataStruct = {
    to: AddressLike;
    amount: BigNumberish;
    nonce: BigNumberish;
  };

  export type DepositDataStructOutput = [
    to: string,
    amount: bigint,
    nonce: bigint
  ] & { to: string; amount: bigint; nonce: bigint };
}

export declare namespace TestBridgeStorageV1 {
  export type StateStruct = { nonce: BigNumberish; root: BytesLike };

  export type StateStructOutput = [nonce: bigint, root: string] & {
    nonce: bigint;
    root: string;
  };

  export type ConfigStruct = {
    fee: BigNumberish;
    minAmount: BigNumberish;
    maxAmount: BigNumberish;
    maxDepositsPerDistribution: BigNumberish;
    gap: [BigNumberish, BigNumberish];
  };

  export type ConfigStructOutput = [
    fee: bigint,
    minAmount: bigint,
    maxAmount: bigint,
    maxDepositsPerDistribution: bigint,
    gap: [bigint, bigint]
  ] & {
    fee: bigint;
    minAmount: bigint;
    maxAmount: bigint;
    maxDepositsPerDistribution: bigint;
    gap: [bigint, bigint];
  };
}

export interface TestBridgeImplV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "claimableGas"
      | "deposit"
      | "gasBridge"
      | "initialize"
      | "isRegistered"
      | "lock"
      | "locked"
      | "managementContract"
      | "register"
      | "setGasMaxNrDepositsPerDistribution"
      | "setGasWithdrawalFee"
      | "setGasWithdrawalMaxAmount"
      | "setGasWithdrawalMinAmount"
      | "unlock"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimable"
      | "Claimed"
      | "Deposit"
      | "Initialized"
      | "Locked"
      | "MaxDepositsPerDistributionChanged"
      | "MaxWithdrawalAmountChanged"
      | "MinWithdrawalAmountChanged"
      | "Unlocked"
      | "Withdrawal"
      | "WithdrawalFeeChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimableGas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      BytesLike,
      TestBridgeImplV2.SignatureStruct[],
      TestBridgeImplV2.DepositDataStruct[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "gasBridge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, TestBridgeStorageV1.ConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lock", values?: undefined): string;
  encodeFunctionData(functionFragment: "locked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "managementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasMaxNrDepositsPerDistribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasWithdrawalFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasWithdrawalMaxAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasWithdrawalMinAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unlock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gasBridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "managementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGasMaxNrDepositsPerDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasWithdrawalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasWithdrawalMaxAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasWithdrawalMinAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ClaimableEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxDepositsPerDistributionChangedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxWithdrawalAmountChangedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinWithdrawalAmountChangedEvent {
  export type InputTuple = [newAmount: BigNumberish];
  export type OutputTuple = [newAmount: bigint];
  export interface OutputObject {
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike,
    from: AddressLike,
    withdrawalHash: BytesLike,
    withdrawalRoot: BytesLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    amount: bigint,
    to: string,
    from: string,
    withdrawalHash: string,
    withdrawalRoot: string
  ];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
    from: string;
    withdrawalHash: string;
    withdrawalRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFeeChangedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestBridgeImplV2 extends BaseContract {
  connect(runner?: ContractRunner | null): TestBridgeImplV2;
  waitForDeployment(): Promise<this>;

  interface: TestBridgeImplV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<[_nonce: BigNumberish], [void], "nonpayable">;

  claimableGas: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;

  deposit: TypedContractMethod<
    [
      _depositRoot: BytesLike,
      _signatures: TestBridgeImplV2.SignatureStruct[],
      _deposits: TestBridgeImplV2.DepositDataStruct[]
    ],
    [void],
    "nonpayable"
  >;

  gasBridge: TypedContractMethod<
    [],
    [
      [
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: TestBridgeStorageV1.StateStructOutput;
        withdrawalState: TestBridgeStorageV1.StateStructOutput;
        config: TestBridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _managementContract: AddressLike,
      config: TestBridgeStorageV1.ConfigStruct
    ],
    [void],
    "nonpayable"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lock: TypedContractMethod<[], [void], "nonpayable">;

  locked: TypedContractMethod<[], [boolean], "view">;

  managementContract: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  setGasMaxNrDepositsPerDistribution: TypedContractMethod<
    [_maxNrDeposits: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasWithdrawalFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasWithdrawalMaxAmount: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasWithdrawalMinAmount: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlock: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[_to: AddressLike], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[_nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableGas"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      _depositRoot: BytesLike,
      _signatures: TestBridgeImplV2.SignatureStruct[],
      _deposits: TestBridgeImplV2.DepositDataStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gasBridge"
  ): TypedContractMethod<
    [],
    [
      [
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: TestBridgeStorageV1.StateStructOutput;
        withdrawalState: TestBridgeStorageV1.StateStructOutput;
        config: TestBridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _managementContract: AddressLike,
      config: TestBridgeStorageV1.ConfigStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "locked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "managementContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasMaxNrDepositsPerDistribution"
  ): TypedContractMethod<[_maxNrDeposits: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasWithdrawalFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasWithdrawalMaxAmount"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasWithdrawalMinAmount"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_to: AddressLike], [void], "payable">;

  getEvent(
    key: "Claimable"
  ): TypedContractEvent<
    ClaimableEvent.InputTuple,
    ClaimableEvent.OutputTuple,
    ClaimableEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Locked"
  ): TypedContractEvent<
    LockedEvent.InputTuple,
    LockedEvent.OutputTuple,
    LockedEvent.OutputObject
  >;
  getEvent(
    key: "MaxDepositsPerDistributionChanged"
  ): TypedContractEvent<
    MaxDepositsPerDistributionChangedEvent.InputTuple,
    MaxDepositsPerDistributionChangedEvent.OutputTuple,
    MaxDepositsPerDistributionChangedEvent.OutputObject
  >;
  getEvent(
    key: "MaxWithdrawalAmountChanged"
  ): TypedContractEvent<
    MaxWithdrawalAmountChangedEvent.InputTuple,
    MaxWithdrawalAmountChangedEvent.OutputTuple,
    MaxWithdrawalAmountChangedEvent.OutputObject
  >;
  getEvent(
    key: "MinWithdrawalAmountChanged"
  ): TypedContractEvent<
    MinWithdrawalAmountChangedEvent.InputTuple,
    MinWithdrawalAmountChangedEvent.OutputTuple,
    MinWithdrawalAmountChangedEvent.OutputObject
  >;
  getEvent(
    key: "Unlocked"
  ): TypedContractEvent<
    UnlockedEvent.InputTuple,
    UnlockedEvent.OutputTuple,
    UnlockedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalFeeChanged"
  ): TypedContractEvent<
    WithdrawalFeeChangedEvent.InputTuple,
    WithdrawalFeeChangedEvent.OutputTuple,
    WithdrawalFeeChangedEvent.OutputObject
  >;

  filters: {
    "Claimable(uint64,uint64,address)": TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;
    Claimable: TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;

    "Claimed(uint64,uint64,address)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Deposit(uint64,uint64,address)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Locked()": TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;
    Locked: TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;

    "MaxDepositsPerDistributionChanged(uint8)": TypedContractEvent<
      MaxDepositsPerDistributionChangedEvent.InputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputObject
    >;
    MaxDepositsPerDistributionChanged: TypedContractEvent<
      MaxDepositsPerDistributionChangedEvent.InputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputObject
    >;

    "MaxWithdrawalAmountChanged(uint256)": TypedContractEvent<
      MaxWithdrawalAmountChangedEvent.InputTuple,
      MaxWithdrawalAmountChangedEvent.OutputTuple,
      MaxWithdrawalAmountChangedEvent.OutputObject
    >;
    MaxWithdrawalAmountChanged: TypedContractEvent<
      MaxWithdrawalAmountChangedEvent.InputTuple,
      MaxWithdrawalAmountChangedEvent.OutputTuple,
      MaxWithdrawalAmountChangedEvent.OutputObject
    >;

    "MinWithdrawalAmountChanged(uint256)": TypedContractEvent<
      MinWithdrawalAmountChangedEvent.InputTuple,
      MinWithdrawalAmountChangedEvent.OutputTuple,
      MinWithdrawalAmountChangedEvent.OutputObject
    >;
    MinWithdrawalAmountChanged: TypedContractEvent<
      MinWithdrawalAmountChangedEvent.InputTuple,
      MinWithdrawalAmountChangedEvent.OutputTuple,
      MinWithdrawalAmountChangedEvent.OutputObject
    >;

    "Unlocked()": TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;
    Unlocked: TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;

    "Withdrawal(uint64,uint64,address,address,bytes32,bytes32)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;

    "WithdrawalFeeChanged(uint256)": TypedContractEvent<
      WithdrawalFeeChangedEvent.InputTuple,
      WithdrawalFeeChangedEvent.OutputTuple,
      WithdrawalFeeChangedEvent.OutputObject
    >;
    WithdrawalFeeChanged: TypedContractEvent<
      WithdrawalFeeChangedEvent.InputTuple,
      WithdrawalFeeChangedEvent.OutputTuple,
      WithdrawalFeeChangedEvent.OutputObject
    >;
  };
}
