/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TestBridgeStorageV1 {
  export type StateStruct = { nonce: BigNumberish; root: BytesLike };

  export type StateStructOutput = [nonce: bigint, root: string] & {
    nonce: bigint;
    root: string;
  };

  export type ConfigStruct = {
    fee: BigNumberish;
    minAmount: BigNumberish;
    maxAmount: BigNumberish;
    maxDepositsPerDistribution: BigNumberish;
    gap: [BigNumberish, BigNumberish];
  };

  export type ConfigStructOutput = [
    fee: bigint,
    minAmount: bigint,
    maxAmount: bigint,
    maxDepositsPerDistribution: bigint,
    gap: [bigint, bigint]
  ] & {
    fee: bigint;
    minAmount: bigint;
    maxAmount: bigint;
    maxDepositsPerDistribution: bigint;
    gap: [bigint, bigint];
  };
}

export interface TestBridgeStorageV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimableGas"
      | "gasBridge"
      | "isRegistered"
      | "locked"
      | "managementContract"
      | "proxyGap"
      | "register"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimableGas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gasBridge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "locked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "managementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxyGap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimableGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "managementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proxyGap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
}

export interface TestBridgeStorageV2 extends BaseContract {
  connect(runner?: ContractRunner | null): TestBridgeStorageV2;
  waitForDeployment(): Promise<this>;

  interface: TestBridgeStorageV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimableGas: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;

  gasBridge: TypedContractMethod<
    [],
    [
      [
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: TestBridgeStorageV1.StateStructOutput;
        withdrawalState: TestBridgeStorageV1.StateStructOutput;
        config: TestBridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  locked: TypedContractMethod<[], [boolean], "view">;

  managementContract: TypedContractMethod<[], [string], "view">;

  proxyGap: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  register: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimableGas"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "gasBridge"
  ): TypedContractMethod<
    [],
    [
      [
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.StateStructOutput,
        TestBridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: TestBridgeStorageV1.StateStructOutput;
        withdrawalState: TestBridgeStorageV1.StateStructOutput;
        config: TestBridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "locked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "managementContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxyGap"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  filters: {};
}
