/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BridgeManagementImpl } from "./BridgeManagementImpl";
export type { IBridgeManagement } from "./IBridgeManagement";
