/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BridgeManagementImpl__factory } from "./BridgeManagementImpl__factory";
export { IBridgeManagement__factory } from "./IBridgeManagement__factory";
