/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BridgeStorageV1 {
  export type StateStruct = { nonce: BigNumberish; root: BytesLike };

  export type StateStructOutput = [nonce: bigint, root: string] & {
    nonce: bigint;
    root: string;
  };

  export type ConfigStruct = {
    fee: BigNumberish;
    minAmount: BigNumberish;
    maxAmount: BigNumberish;
    maxDepositsPerDistribution: BigNumberish;
    gap: [BigNumberish, BigNumberish];
  };

  export type ConfigStructOutput = [
    fee: bigint,
    minAmount: bigint,
    maxAmount: bigint,
    maxDepositsPerDistribution: bigint,
    gap: [bigint, bigint]
  ] & {
    fee: bigint;
    minAmount: bigint;
    maxAmount: bigint;
    maxDepositsPerDistribution: bigint;
    gap: [bigint, bigint];
  };
}

export interface BridgeStorageV1Interface extends Interface {
  getFunction(
    nameOrSignature: "claimableGas" | "gasBridge" | "locked"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimableGas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gasBridge", values?: undefined): string;
  encodeFunctionData(functionFragment: "locked", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "claimableGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasBridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
}

export interface BridgeStorageV1 extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeStorageV1;
  waitForDeployment(): Promise<this>;

  interface: BridgeStorageV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimableGas: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;

  gasBridge: TypedContractMethod<
    [],
    [
      [
        BridgeStorageV1.StateStructOutput,
        BridgeStorageV1.StateStructOutput,
        BridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: BridgeStorageV1.StateStructOutput;
        withdrawalState: BridgeStorageV1.StateStructOutput;
        config: BridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;

  locked: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimableGas"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { to: string; amount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "gasBridge"
  ): TypedContractMethod<
    [],
    [
      [
        BridgeStorageV1.StateStructOutput,
        BridgeStorageV1.StateStructOutput,
        BridgeStorageV1.ConfigStructOutput
      ] & {
        depositState: BridgeStorageV1.StateStructOutput;
        withdrawalState: BridgeStorageV1.StateStructOutput;
        config: BridgeStorageV1.ConfigStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "locked"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
