/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AppLogsBridgeContract {
  export type SignatureStruct = { v: BigNumberish; r: BytesLike; s: BytesLike };

  export type SignatureStructOutput = [v: bigint, r: string, s: string] & {
    v: bigint;
    r: string;
    s: string;
  };

  export type DepositWithProofStruct = {
    to: AddressLike;
    amount: BigNumberish;
    nonce: BigNumberish;
    path: BigNumberish;
    proof: BytesLike[];
  };

  export type DepositWithProofStructOutput = [
    to: string,
    amount: bigint,
    nonce: bigint,
    path: bigint,
    proof: string[]
  ] & {
    to: string;
    amount: bigint;
    nonce: bigint;
    path: bigint;
    proof: string[];
  };
}

export interface AppLogsBridgeContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimableAmount"
      | "claimableTo"
      | "deposit"
      | "depositNonce"
      | "depositRoot"
      | "relayer"
      | "validators"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Claimable" | "Withdrawal"): EventFragment;

  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableTo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      BytesLike,
      AppLogsBridgeContract.SignatureStruct[],
      AppLogsBridgeContract.DepositWithProofStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRoot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
}

export namespace ClaimableEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AppLogsBridgeContract extends BaseContract {
  connect(runner?: ContractRunner | null): AppLogsBridgeContract;
  waitForDeployment(): Promise<this>;

  interface: AppLogsBridgeContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimableAmount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  claimableTo: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deposit: TypedContractMethod<
    [
      _newDepositRoot: BytesLike,
      _signatures: AppLogsBridgeContract.SignatureStruct[],
      _deposits: AppLogsBridgeContract.DepositWithProofStruct[]
    ],
    [void],
    "nonpayable"
  >;

  depositNonce: TypedContractMethod<[], [bigint], "view">;

  depositRoot: TypedContractMethod<[], [string], "view">;

  relayer: TypedContractMethod<[], [string], "view">;

  validators: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimableTo"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      _newDepositRoot: BytesLike,
      _signatures: AppLogsBridgeContract.SignatureStruct[],
      _deposits: AppLogsBridgeContract.DepositWithProofStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "Claimable"
  ): TypedContractEvent<
    ClaimableEvent.InputTuple,
    ClaimableEvent.OutputTuple,
    ClaimableEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "Claimable(uint64,uint64,address)": TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;
    Claimable: TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;

    "Withdrawal(uint64,uint64,address)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
