/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BridgeContract {
  export type SignatureStruct = { v: BigNumberish; r: BytesLike; s: BytesLike };

  export type SignatureStructOutput = [v: bigint, r: string, s: string] & {
    v: bigint;
    r: string;
    s: string;
  };

  export type DepositDataStruct = {
    to: AddressLike;
    amount: BigNumberish;
    nonce: BigNumberish;
  };

  export type DepositDataStructOutput = [
    to: string,
    amount: bigint,
    nonce: bigint
  ] & { to: string; amount: bigint; nonce: bigint };
}

export interface BridgeContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "claimableAmount"
      | "claimableTo"
      | "deposit"
      | "depositNonce"
      | "depositRoot"
      | "lock"
      | "locked"
      | "unlock"
      | "withdraw"
      | "withdrawalNonce"
      | "withdrawalRoot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimable"
      | "Claimed"
      | "Deposit"
      | "MaxDepositsPerDistributionChanged"
      | "MaxWithdrawalAmountChanged"
      | "MinWithdrawalAmountChanged"
      | "Withdrawal"
      | "WithdrawalFeeChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableTo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      BytesLike,
      BridgeContract.SignatureStruct[],
      BridgeContract.DepositDataStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRoot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lock", values?: undefined): string;
  encodeFunctionData(functionFragment: "locked", values?: undefined): string;
  encodeFunctionData(functionFragment: "unlock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRoot",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRoot",
    data: BytesLike
  ): Result;
}

export namespace ClaimableEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [nonce: bigint, amount: bigint, to: string];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxDepositsPerDistributionChangedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxWithdrawalAmountChangedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinWithdrawalAmountChangedEvent {
  export type InputTuple = [newAmount: BigNumberish];
  export type OutputTuple = [newAmount: bigint];
  export interface OutputObject {
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    amount: BigNumberish,
    to: AddressLike,
    from: AddressLike,
    withdrawalHash: BytesLike,
    withdrawalRoot: BytesLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    amount: bigint,
    to: string,
    from: string,
    withdrawalHash: string,
    withdrawalRoot: string
  ];
  export interface OutputObject {
    nonce: bigint;
    amount: bigint;
    to: string;
    from: string;
    withdrawalHash: string;
    withdrawalRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFeeChangedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeContract extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeContract;
  waitForDeployment(): Promise<this>;

  interface: BridgeContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<[_nonce: BigNumberish], [void], "nonpayable">;

  claimableAmount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  claimableTo: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deposit: TypedContractMethod<
    [
      _depositRoot: BytesLike,
      _signatures: BridgeContract.SignatureStruct[],
      _deposits: BridgeContract.DepositDataStruct[]
    ],
    [void],
    "nonpayable"
  >;

  depositNonce: TypedContractMethod<[], [bigint], "view">;

  depositRoot: TypedContractMethod<[], [string], "view">;

  lock: TypedContractMethod<[], [void], "nonpayable">;

  locked: TypedContractMethod<[], [boolean], "view">;

  unlock: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[_to: AddressLike], [void], "payable">;

  withdrawalNonce: TypedContractMethod<[], [bigint], "view">;

  withdrawalRoot: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[_nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimableTo"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      _depositRoot: BytesLike,
      _signatures: BridgeContract.SignatureStruct[],
      _deposits: BridgeContract.DepositDataStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "locked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "unlock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_to: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "withdrawalNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawalRoot"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Claimable"
  ): TypedContractEvent<
    ClaimableEvent.InputTuple,
    ClaimableEvent.OutputTuple,
    ClaimableEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "MaxDepositsPerDistributionChanged"
  ): TypedContractEvent<
    MaxDepositsPerDistributionChangedEvent.InputTuple,
    MaxDepositsPerDistributionChangedEvent.OutputTuple,
    MaxDepositsPerDistributionChangedEvent.OutputObject
  >;
  getEvent(
    key: "MaxWithdrawalAmountChanged"
  ): TypedContractEvent<
    MaxWithdrawalAmountChangedEvent.InputTuple,
    MaxWithdrawalAmountChangedEvent.OutputTuple,
    MaxWithdrawalAmountChangedEvent.OutputObject
  >;
  getEvent(
    key: "MinWithdrawalAmountChanged"
  ): TypedContractEvent<
    MinWithdrawalAmountChangedEvent.InputTuple,
    MinWithdrawalAmountChangedEvent.OutputTuple,
    MinWithdrawalAmountChangedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalFeeChanged"
  ): TypedContractEvent<
    WithdrawalFeeChangedEvent.InputTuple,
    WithdrawalFeeChangedEvent.OutputTuple,
    WithdrawalFeeChangedEvent.OutputObject
  >;

  filters: {
    "Claimable(uint64,uint64,address)": TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;
    Claimable: TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;

    "Claimed(uint64,uint64,address)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Deposit(uint64,uint64,address)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "MaxDepositsPerDistributionChanged(uint8)": TypedContractEvent<
      MaxDepositsPerDistributionChangedEvent.InputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputObject
    >;
    MaxDepositsPerDistributionChanged: TypedContractEvent<
      MaxDepositsPerDistributionChangedEvent.InputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputTuple,
      MaxDepositsPerDistributionChangedEvent.OutputObject
    >;

    "MaxWithdrawalAmountChanged(uint256)": TypedContractEvent<
      MaxWithdrawalAmountChangedEvent.InputTuple,
      MaxWithdrawalAmountChangedEvent.OutputTuple,
      MaxWithdrawalAmountChangedEvent.OutputObject
    >;
    MaxWithdrawalAmountChanged: TypedContractEvent<
      MaxWithdrawalAmountChangedEvent.InputTuple,
      MaxWithdrawalAmountChangedEvent.OutputTuple,
      MaxWithdrawalAmountChangedEvent.OutputObject
    >;

    "MinWithdrawalAmountChanged(uint256)": TypedContractEvent<
      MinWithdrawalAmountChangedEvent.InputTuple,
      MinWithdrawalAmountChangedEvent.OutputTuple,
      MinWithdrawalAmountChangedEvent.OutputObject
    >;
    MinWithdrawalAmountChanged: TypedContractEvent<
      MinWithdrawalAmountChangedEvent.InputTuple,
      MinWithdrawalAmountChangedEvent.OutputTuple,
      MinWithdrawalAmountChangedEvent.OutputObject
    >;

    "Withdrawal(uint64,uint64,address,address,bytes32,bytes32)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;

    "WithdrawalFeeChanged(uint256)": TypedContractEvent<
      WithdrawalFeeChangedEvent.InputTuple,
      WithdrawalFeeChangedEvent.OutputTuple,
      WithdrawalFeeChangedEvent.OutputObject
    >;
    WithdrawalFeeChanged: TypedContractEvent<
      WithdrawalFeeChangedEvent.InputTuple,
      WithdrawalFeeChangedEvent.OutputTuple,
      WithdrawalFeeChangedEvent.OutputObject
    >;
  };
}
