/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Bridge {
  export type MerkleProofStruct = {
    nonce: BigNumberish;
    to: AddressLike;
    amount: BigNumberish;
    path: BigNumberish;
    proof: BytesLike[];
  };

  export type MerkleProofStructOutput = [
    nonce: bigint,
    to: string,
    amount: bigint,
    path: bigint,
    proof: string[]
  ] & {
    nonce: bigint;
    to: string;
    amount: bigint;
    path: bigint;
    proof: string[];
  };

  export type SignatureStruct = { v: BigNumberish; r: BytesLike; s: BytesLike };

  export type SignatureStructOutput = [v: bigint, r: string, s: string] & {
    v: bigint;
    r: string;
    s: string;
  };
}

export interface BridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim((uint64,address,uint64,uint64,bytes32[]))"
      | "claim((uint64,address,uint64,uint64,bytes32[]),uint256)"
      | "claimableDeposits"
      | "deposit"
      | "depositNonce"
      | "depositRoot"
      | "maxWithdrawalAmount"
      | "minWithdrawalAmount"
      | "relayer"
      | "rootMap"
      | "validators"
      | "withdraw"
      | "withdrawalNonce"
      | "withdrawalRoot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Claimable" | "Claimed" | "Deposit" | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claim((uint64,address,uint64,uint64,bytes32[]))",
    values: [Bridge.MerkleProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "claim((uint64,address,uint64,uint64,bytes32[]),uint256)",
    values: [Bridge.MerkleProofStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableDeposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      BytesLike,
      BigNumberish,
      Bridge.SignatureStruct[],
      Bridge.MerkleProofStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdrawalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minWithdrawalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rootMap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRoot",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "claim((uint64,address,uint64,uint64,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claim((uint64,address,uint64,uint64,bytes32[]),uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdrawalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minWithdrawalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rootMap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRoot",
    data: BytesLike
  ): Result;
}

export namespace ClaimableEvent {
  export type InputTuple = [_nonce: BigNumberish];
  export type OutputTuple = [_nonce: bigint];
  export interface OutputObject {
    _nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [_nonce: BigNumberish];
  export type OutputTuple = [_nonce: bigint];
  export interface OutputObject {
    _nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    _nonce: BigNumberish,
    _to: AddressLike,
    _value: BigNumberish
  ];
  export type OutputTuple = [_nonce: bigint, _to: string, _value: bigint];
  export interface OutputObject {
    _nonce: bigint;
    _to: string;
    _value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    _nonce: BigNumberish,
    from: AddressLike,
    _to: AddressLike,
    _amount: BigNumberish,
    _withdrawalHash: BytesLike,
    _root: BytesLike
  ];
  export type OutputTuple = [
    _nonce: bigint,
    from: string,
    _to: string,
    _amount: bigint,
    _withdrawalHash: string,
    _root: string
  ];
  export interface OutputObject {
    _nonce: bigint;
    from: string;
    _to: string;
    _amount: bigint;
    _withdrawalHash: string;
    _root: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Bridge extends BaseContract {
  connect(runner?: ContractRunner | null): Bridge;
  waitForDeployment(): Promise<this>;

  interface: BridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "claim((uint64,address,uint64,uint64,bytes32[]))": TypedContractMethod<
    [_proof: Bridge.MerkleProofStruct],
    [void],
    "nonpayable"
  >;

  "claim((uint64,address,uint64,uint64,bytes32[]),uint256)": TypedContractMethod<
    [_proof: Bridge.MerkleProofStruct, gas: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimableDeposits: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  deposit: TypedContractMethod<
    [
      _depositRoot: BytesLike,
      _lastNonce: BigNumberish,
      _signatures: Bridge.SignatureStruct[],
      _proofs: Bridge.MerkleProofStruct[]
    ],
    [void],
    "nonpayable"
  >;

  depositNonce: TypedContractMethod<[], [bigint], "view">;

  depositRoot: TypedContractMethod<[], [string], "view">;

  maxWithdrawalAmount: TypedContractMethod<[], [bigint], "view">;

  minWithdrawalAmount: TypedContractMethod<[], [bigint], "view">;

  relayer: TypedContractMethod<[], [string], "view">;

  rootMap: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  validators: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  withdraw: TypedContractMethod<[_to: AddressLike], [void], "payable">;

  withdrawalNonce: TypedContractMethod<[], [bigint], "view">;

  withdrawalRoot: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim((uint64,address,uint64,uint64,bytes32[]))"
  ): TypedContractMethod<
    [_proof: Bridge.MerkleProofStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim((uint64,address,uint64,uint64,bytes32[]),uint256)"
  ): TypedContractMethod<
    [_proof: Bridge.MerkleProofStruct, gas: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimableDeposits"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      _depositRoot: BytesLike,
      _lastNonce: BigNumberish,
      _signatures: Bridge.SignatureStruct[],
      _proofs: Bridge.MerkleProofStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxWithdrawalAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minWithdrawalAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rootMap"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_to: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "withdrawalNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawalRoot"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Claimable"
  ): TypedContractEvent<
    ClaimableEvent.InputTuple,
    ClaimableEvent.OutputTuple,
    ClaimableEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "Claimable(uint64)": TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;
    Claimable: TypedContractEvent<
      ClaimableEvent.InputTuple,
      ClaimableEvent.OutputTuple,
      ClaimableEvent.OutputObject
    >;

    "Claimed(uint64)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Deposit(uint64,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Withdrawal(uint64,address,address,uint256,bytes32,bytes32)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
