/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AppLogsBridgeContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AppLogsBridgeContract__factory>;
    getContractFactory(
      name: "HashTreeBridgeContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HashTreeBridgeContract__factory>;
    getContractFactory(
      name: "TestPayableContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestPayableContract__factory>;

    getContractAt(
      name: "AppLogsBridgeContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AppLogsBridgeContract>;
    getContractAt(
      name: "HashTreeBridgeContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HashTreeBridgeContract>;
    getContractAt(
      name: "TestPayableContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestPayableContract>;

    deployContract(
      name: "AppLogsBridgeContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AppLogsBridgeContract>;
    deployContract(
      name: "HashTreeBridgeContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashTreeBridgeContract>;
    deployContract(
      name: "TestPayableContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestPayableContract>;

    deployContract(
      name: "AppLogsBridgeContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AppLogsBridgeContract>;
    deployContract(
      name: "HashTreeBridgeContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HashTreeBridgeContract>;
    deployContract(
      name: "TestPayableContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestPayableContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
