/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BridgeContract } from "./BridgeContract";
export type { TestPayableContract } from "./TestPayableContract";
export * as factories from "./factories";
export { BridgeContract__factory } from "./factories/BridgeContract__factory";
export { TestPayableContract__factory } from "./factories/TestPayableContract__factory";
